name: 1001crosses
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools
  - bedtools
  - bwa
  - cutadapt
  - bioconda::cyvcf2
  - fastqc
  - conda-forge::filelock
  - bioconda::gcta 
  - gemma
  - ipykernel
  - conda-forge::limix-plot
  - minimap2
  - multiqc
  - conda-forge::ncurses
  - numpy
  - pandas==2.2.2
  - parallel
  - picard
  - pip
  - plink
  - plink2
  - python>3.10
  - conda-forge::quarto
  - r-base==4.2.0
  - r-ggplot2
  - conda-forge::r-ggpubr
  - r::r-ggpointdensity
  - conda-forge::r-htmlwidgets
  - conda-forge::r-manhattanly
  - conda-forge::r-optparse
  - conda-forge::r-quarto
  - conda-forge::r-qqman
  - conda-forge::r-rprojroot
  - conda-forge::r-tinytex
  - conda-forge::r-vcfr==1.12.0 
  - r-vctrs=0.5.1
  - samtools
  - scipy
  - tabix
  - trim-galore
  - vcftools
  - pip:
    - ibdpainting
    - methlab
    - statsmodels
    - scikit-allel
